// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Reduced_Rank_COAP
Rcpp::List Reduced_Rank_COAP(const arma::mat& X_count, const arma::vec& a, const arma::mat& Z, const int& rank_use, const arma::mat& Mu_y_int, const arma::mat& S_y_int, const arma::vec& invLambda_int, const arma::mat& B_int, const arma::mat& bbeta_int, const arma::mat& H_int, const double& epsELBO, const int& maxIter, const bool& verbose, const bool& sep_opt_beta, const bool& fast_svd);
RcppExport SEXP _COAP_Reduced_Rank_COAP(SEXP X_countSEXP, SEXP aSEXP, SEXP ZSEXP, SEXP rank_useSEXP, SEXP Mu_y_intSEXP, SEXP S_y_intSEXP, SEXP invLambda_intSEXP, SEXP B_intSEXP, SEXP bbeta_intSEXP, SEXP H_intSEXP, SEXP epsELBOSEXP, SEXP maxIterSEXP, SEXP verboseSEXP, SEXP sep_opt_betaSEXP, SEXP fast_svdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_count(X_countSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int& >::type rank_use(rank_useSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mu_y_int(Mu_y_intSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_y_int(S_y_intSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type invLambda_int(invLambda_intSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B_int(B_intSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bbeta_int(bbeta_intSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H_int(H_intSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsELBO(epsELBOSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type sep_opt_beta(sep_opt_betaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type fast_svd(fast_svdSEXP);
    rcpp_result_gen = Rcpp::wrap(Reduced_Rank_COAP(X_count, a, Z, rank_use, Mu_y_int, S_y_int, invLambda_int, B_int, bbeta_int, H_int, epsELBO, maxIter, verbose, sep_opt_beta, fast_svd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_COAP_Reduced_Rank_COAP", (DL_FUNC) &_COAP_Reduced_Rank_COAP, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_COAP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
