# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
#' 
NULL

Reduced_Rank_COAP <- function(X_count, a, Z, rank_use, Mu_y_int, S_y_int, invLambda_int, B_int, bbeta_int, Mu_h_int, S_h_int, Sigma_h_int, epsELBO, maxIter, verbose, fast_version, sep_opt_beta, fast_svd = TRUE) {
    .Call(`_COAP_Reduced_Rank_COAP`, X_count, a, Z, rank_use, Mu_y_int, S_y_int, invLambda_int, B_int, bbeta_int, Mu_h_int, S_h_int, Sigma_h_int, epsELBO, maxIter, verbose, fast_version, sep_opt_beta, fast_svd)
}

